import { z } from 'astro/zod';
import handsJson from './hands.json';

// The glyph hands of the pill scene, generated by scripts/build-hands.mjs. One hand per size, the other one is
// its mirror image. One digit per cell: 0 is empty, 1..4 is the density of the hand, 6..9 the same density on the
// capsule (5 is not used).
const gridSchema = z
  .strictObject({
    cols: z.number().int().positive(),
    rows: z.number().int().positive(),
    levels: z.array(z.string()),
    // The middle of the capsule and its radius, in cells: the real button lies over it.
    pill: z.strictObject({ x: z.number().positive(), y: z.number().positive(), r: z.number().positive() }),
  })
  .refine(
    grid =>
      grid.levels.length === grid.rows && grid.levels.every(row => row.length === grid.cols && /^[0-46-9]+$/.test(row)),
    'levels must be rows × cols digits 0..4 and 6..9'
  );

export const handsSchema = z.strictObject({ desktop: gridSchema, mobile: gridSchema });

export const hands = handsSchema.parse(handsJson);
