import { z } from 'astro/zod';
import maskJson from './mask.json';

// The glyph mask of the netrunner (J-07), generated by scripts/build-mask.mjs. One character per cell:
// 0 is empty, 1…4 is the mask itself (pale), 6…9 the digital parts (cyan: the eyes and the circuits), a…d the hood (red);
// the number is the density of the glyph. (5 is not used.)
const gridSchema = z
  .strictObject({
    cols: z.number().int().positive(),
    rows: z.number().int().positive(),
    levels: z.array(z.string()),
  })
  .refine(
    grid =>
      grid.levels.length === grid.rows &&
      grid.levels.every(row => row.length === grid.cols && /^[0-46-9a-d]+$/.test(row)),
    'levels must be rows × cols characters 0..4, 6..9 and a..d'
  );

export const maskSchema = z.strictObject({
  // Width over height of the picture as it is meant to be shown.
  ratio: z.number().positive(),
  desktop: gridSchema,
  mobile: gridSchema,
});

export const mask = maskSchema.parse(maskJson);
