import { z } from 'astro/zod';
import wordmarkJson from './wordmark.json';

// Density levels of the glyph wordmarks, generated by scripts/build-wordmark.mjs. One digit per cell:
// 0 is empty, 4 is the densest.
const gridSchema = z
  .strictObject({
    cols: z.number().int().positive(),
    rows: z.number().int().positive(),
    levels: z.array(z.string()),
  })
  .refine(
    grid =>
      grid.levels.length === grid.rows && grid.levels.every(row => row.length === grid.cols && /^[0-4]+$/.test(row)),
    'levels must be rows × cols digits 0..4'
  );

const variantsSchema = z.strictObject({ desktop: gridSchema, mobile: gridSchema });

export const wordmarkSchema = z.strictObject({ mirislamus: variantsSchema, '404': variantsSchema });

export type WordmarkName = keyof z.infer<typeof wordmarkSchema>;
export type WordmarkGrid = z.infer<typeof gridSchema>;

export const wordmarks = wordmarkSchema.parse(wordmarkJson);
